language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack:
    secure: "kM79t9nqpjd8isbA8ylglAczdxAk6D8gsaBXRbB4t33hnxdlHafYss2yy7c2/gv2rezH/yp1NVEB+40EknodtX/idBRO8VbPZ/DMzAL9UmdJNgHIaJ4MjKAz9kg0jC5NOGRYKEcMM/J5i8f8kzpqoqBhxL+9AQHgHLc4AnYD/Jx0HHM4t3cRXM8PLHboPBrCbIMSIqX5g/IZ+iS0Oo9nusx+aWdNBoNFw7igECxLy/CCKinUAkIc9WV298eTwHw3vFUOHPzzqIv3PJxOxELoqZ7TmC8Rn4Ts7yLf4KRgpNJnvp9uS6s3FBK7enLvURk6QeTZEfMBoqT6R9a+VxxbKfmoHE0gwqrqKP/ylkflw8UwiiuI7tCbUarAqYlJu0dd2eK3OVm4vQZTxydXlA/Nt47LstlMz9VPD2kwvTwDKtIHPDBAhS0OpBFV4gAakOPdjxZNVQc90DGGQKAFcVZfhPLnyk5xspwZt/PYNC2isbQFfrt9e1feckfV0eoh1nnchZ38fN0Hkzu8LY/YeQsgFukmFelEkBRdZTHkBRO/tCTJoCkr64ST01oKqj7eW/WLeOaw5BffqvNHmBdPvqZCsa3EePPJCJxUCCnK+ezzG7YIlZ6IBs1yGqsIywJbjgZyabmGGeWJBBpaIBcVyuk/xWo58G9rIjysLfxHywuAftg="
  email:
    recipients:
      - oscar@platzi.com
      - oscar@arepa.dev
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "sKXWjYlRJ9SDp3C8uEFVo4tD1yRd4caZcSAbmmgJx88A2tSNKbijJFFMlQgD32cGBgISwtDXnIcbd15lK3z3LYw8nywsLl2woB4keL5vgwm4r97bCxvYQDH28Y4h44z+lQYlUBD0qmTFcgRKpKp5mUts27XhsqUC4XLFqwDgWy7M9mzrxO2/RkZD7WScI+SiDJq9TTFMooRIIdstACQ812yHdRH4UGh2mYNC/zoovnXpdYg/1i9iWMj/aFnr7Hh53WABhL9O0Wfq4EoOxs9N6iXxivyw3mST6q+6rGt/yvDsyNGSUcUphYEJpC+33iwYSS0ogFqhKPoJyaV4gwoGGF3XsHd63fFOVi/af+WGThN9LEmYmpi7pQevdrtUhfsZ/mlkRCQDLi9sAqBc1Sgyv5oOZl/PkXpbwZlWDh1c0pKtcqGyc+zA4KG4DcIT2YiRcfookm0X29oEBYAaa4p4mmzB1Lf6BmSCYJI8bZ9WKX1UzMIMrNecHbltRYe1akxkiUKqsEH/N4OdrmsGd0R2vmQU0Gnraq81pNnp5rGdiKDWc0bQShQIueqUyWDDMotDvKFaCXl7VNMiuC+ORloeY5ZbHsSoLqBwSRL+bPqEEQbI26KFBqDhwDAm1jCc4djBmsy40dSW6p4B2B77KnjQMpxJoW87rGlcjs58JqFm5gA="
  app: platzi-store-backend
  on:
    repo: Chewiekie/platzi-store-backend