language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack: localmeetups-co:xTc4oYzejXFFNHsAaYEzxIkE
  email:
    recipients:
      - oscar@platzi.com
      - oscar@arepa.dev
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: f4273f2a-9430-4302-98f1-ddb90d7ea913
  app: platzi-store-backend
  on:
    repo: Chewiekie/platzi-store-backend